version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=restaurant_eval
      - POSTGRES_PASSWORD=password

  nnpia-adminer:
    image: adminer
    ports:
      - "8001:8080"




