version: "3.8"
services:
  db:
    image: postgres:latest
    command:
      - "postgres"
      - "--shared_buffers=1GB"
    environment:
      PGUSER: nnpia
      POSTGRES_USER: nnpia
      POSTGRES_PASSWORD: nnpia
      PGDATA: /data/postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  nnpia-adminer:
    image: adminer
    ports:
      - "8001:8080"




